spring:
  application:
    name: template-app
  jackson:
    default-property-inclusion: non_null
    property-naming-strategy: SNAKE_CASE
  main:
    lazy-initialization: true
  config:
    location: file://./src/main/resources/application.yml
  jmx:
    enabled: false

server:
  port: 8081
  error:
    whitelabel:
      enabled: false

management:
  server:
    port: 8082
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health
info:
  app:
    name: @project.name@
    description: @project.description@
    version: @project.version@